services:
  postgres:
    image: postgres:16-alpine
    container_name: diabetes_expert_postgres
    environment:
      POSTGRES_DB: diabetes_expert_db
      POSTGRES_USER: expert_user
      POSTGRES_PASSWORD: expert_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:

